### ISSUE TITLE
Brain Write

### ISSUE THREAD

**Issue by aaditgupta21** [aaditgupta21/silverscreen#6]

**Comment by rohitd3** [comment]
1. Best Selling Movies of all Time
2. Recent Movies that Came out
3. Movies that are playing near me
4. Random Movie Generator
5. Random Movie Generator
6. Best Selling Shows of all time
7. Recent Shows that came out
8. Top Rated Show
9. Random Show Generator
10. Movie Commenting/Reviews
11. Find Movies by Actor Name
12. List actors in movie
13. Find Movie Information i.e Release date, Director, blurb
